version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  wordpress:
    build: 
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    build: 
      context: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge