# 서비스 정의 (각 서비스는 개별 컨테이너로 생성됨)
services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception-network
    init: true

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception-network
    init: true
      
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception-network
    init: true


# 볼륨 정의
volumes:
  mariadb_data:
    driver: local   # 호스트 시스템의 디스크에 저장
    driver_opts:
      type: none # 이미 존재하는 디랙토리를 마운트
      o: bind # 볼륨이 호스트 시스템의 특정 디렉토리에 직접 연결됨
      device: /home/${USER}/data/mariadb # 호스트시스템이서 마운트 할 경로
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

# 네트워크 정의
networks:
  inception-network:
    driver: bridge