services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build:  ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
      
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception





volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

networks:
  inception:
    name: inception
    driver: bridge