FROM debian:bullseye

# MariaDB 설치
# dumb-init은 PID 1로 실행되는 init 프로세스 역할을 합니다.
# MariaDB 서버와 클라이언트를 함께 설치합니다.
# apt update로 다운로드된 패키지 목록 캐시를 삭제하여 이미지 크기를 줄이는 역할을 합니다.
RUN apt-get update && apt-get install -y \
	dumb-init \
	mariadb-server \
	mariadb-client \
	&& rm -rf /var/lib/apt/lists/* 


#mysql 디렉터리 설정
RUN mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql

#설정파일, 초기화스크립트 복사
COPY ./conf/mariadb.cnf /etc/mysql/mariadb.cnf
COPY ./tools/database_setup.sh /home/database_setup.sh

#실행권한부여
RUN chmod +x /home/database_setup.sh

EXPOSE 3306

ENTRYPOINT ["/home/database_setup.sh"]