# 

FROM debian:bullseye

RUN apt update && apt install -y \
	php \
	php-mysql \
	php-fpm \
	php-curl \
	php-gd \
	php-intl \
	php-mbstring \
	php-soap \
	php-xml \
	php-xmlrpc \
	php-zip \
	curl \
	wget \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf
# COPY ./tools/wordpress_setup.sh /home/wordpress_setup.sh
COPY ./tools/wordpress_setup.sh /usr/local/bin/
# RUN chmod +x /home/wordpress_setup.sh
RUN chmod +x /usr/local/bin/wordpress_setup.sh
RUN mkdir -p /run/php

EXPOSE 9000

CMD ["/usr/local/bin/wordpress_setup.sh"]