FROM debian:bullseye

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    php7.3-fpm \
    php7.3-mysql \
    curl \
    mariadb-client

# WordPress 다운로드 및 설치
WORKDIR /var/www/html
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

# php-fpm 설정
RUN mkdir -p /run/php
COPY conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf

# WordPress 설치 스크립트 복사 및 실행 권한 부여
COPY tools/wordpress_setup.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wordpress_setup.sh

EXPOSE 9000

CMD ["/usr/local/bin/wordpress_setup.sh"]