# FROM debian:bullseye

# RUN apt-get update && apt-get install -y nginx openssl
# # RUN apt-get update && apt-get install -y \
# # 	nginx \
# 	# openssl \
# 	# && rm -rf /var/lib/apt/lists/*
# RUN mkdir -p /etc/nginx/ssl

# RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#     -keyout /etc/nginx/ssl/nginx.key \
#     -out /etc/nginx/ssl/nginx.crt \
#     -subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=42/CN=localhost"

# #포그라운드에서 nginx를 실행
# # CMD ["nginx", "-g", "daemon off;"]

# # nginx 설정 파일 복사
# COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

# # 443 포트 개방
# EXPOSE 443

# # nginx 실행
# CMD ["nginx", "-g", "daemon off;"]
FROM debian:bullseye

RUN apt-get update && apt-get install -y nginx openssl

# SSL 인증서 생성
RUN mkdir /etc/nginx/ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=42/CN=localhost"

# nginx 설정 파일 복사
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

# 443 포트 개방
EXPOSE 443

# nginx 실행
CMD ["nginx", "-g", "daemon off;"]