FROM debian:bullseye


RUN apt-get update && apt-get install -y \
	nginx \
	openssl \
	&& rm -rf /var/lib/apt/lists/*



# nginx 설정 파일 복사
COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./tools/nginx.sh /home/nginx.sh
RUN chmod +x /home/nginx.sh

# 443 포트 개방
EXPOSE 443

ENTRYPOINT ["/home/nginx.sh"]
